"""EN / 中文 (#116, #121): the Chinese edition's finishing pass, and the terms it names.

The Chinese edition is built from the Chinese sources by the same templates as the English one
(build_site.write_edition). Two things are left for this pass, over every page in `zh/`:

* **Links.** The pages are written with the English edition's base (`..`) so assets, figures and
  recordings resolve one level up; a link to another *page* is pointed back inside `zh/`.
* **The site's own words.** Short labels the templates write (modes, buttons, kickers, counts) are
  changed with `ui-zh.json` — the same table `locale.js` uses for labels scripts write later.
  Sentences with markup are written in both languages in the templates themselves (`SH.T`).

`english_residue()` is the check that the result reads as Chinese: a run of English words outside
code is a template string no one translated. `terms-zh.json` gives every glossary term its Chinese
name and definition — the names the translation uses.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

SITE = Path(__file__).resolve().parent
TERMS_PATH = SITE.parent / "06-production" / "terms-zh.json"
UI_PATH = SITE / "ui-zh.json"


def load() -> dict[str, dict]:
    return json.loads(TERMS_PATH.read_text(encoding="utf-8"))["terms"]


def stem(term: str) -> str:
    """What a term looks like in running text: `Context window (recentContext)` is written
    "context window"."""
    return re.sub(r"\s*\([^)]*\)\s*$", "", term.replace("`", "")).strip()


# ---------------------------------------------------------------- the site's own words

def ui_table() -> dict:
    return json.loads(UI_PATH.read_text(encoding="utf-8"))


def ui_script() -> str:
    """assets/ui-zh.js: the table, for locale.js."""
    t = ui_table()
    data = {"exact": t["exact"], "patterns": t["patterns"]}
    return ("/* Generated by build_site.py from ui-zh.json — do not edit. */\n"
            "window.APSUiZh = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")


class Labels:
    def __init__(self, table: dict):
        self.exact = table["exact"]
        self.patterns = [(re.compile(p), re.sub(r"\$(\d)", r"\\\1", r)) for p, r in table["patterns"]]

    def one(self, t: str) -> str | None:
        if t in self.exact:
            return self.exact[t]
        for rx, rep in self.patterns:
            if rx.search(t):
                return rx.sub(rep, t)
        return None

    def __call__(self, text: str) -> str | None:
        t = text.strip()
        if not t:
            return None
        whole = self.one(t)
        if whole is not None:
            return text.replace(t, whole)
        for sep in (" · ", " — "):
            if sep not in t:
                continue
            pieces = t.split(sep)
            out = [self.one(p) for p in pieces]
            if any(o is not None for o in out):
                return text.replace(t, sep.join(o if o is not None else p for o, p in zip(out, pieces)))
        return None


SKIP = {"script", "style", "pre", "code", "textarea", "kbd"}
TAG = re.compile(r"(<[^>]+>)")
TAG_NAME = re.compile(r"^<\s*(/?)\s*([a-zA-Z0-9]+)")
ATTRS = re.compile(r'\b(aria-label|title|placeholder|alt|content|data-unit-label|data-deck-label)="([^"]*)"')


def _walk(page: str):
    """(is_tag, piece, skipped) over a page, where `skipped` is inside script/style/pre/code/kbd."""
    depth = 0
    for piece in TAG.split(page):
        if not piece:
            continue
        if piece.startswith("<"):
            m = TAG_NAME.match(piece)
            if m and m.group(2).lower() in SKIP and not piece.endswith("/>"):
                if m.group(1):
                    depth = max(0, depth - 1)
                    yield True, piece, depth > 0
                else:
                    yield True, piece, depth > 0
                    depth += 1
                continue
            yield True, piece, depth > 0
        else:
            yield False, piece, depth > 0


def localize(page: str, labels: Labels) -> str:
    out = []
    for is_tag, piece, skipped in _walk(page):
        if is_tag:
            if not skipped:
                piece = ATTRS.sub(lambda m: f'{m.group(1)}="{_attr(m.group(2), labels)}"', piece)
            out.append(piece)
        elif skipped:
            out.append(piece)
        else:
            zh = labels(html.unescape(piece))
            out.append(html.escape(zh, quote=False) if zh is not None else piece)
    return "".join(out)


def _attr(value: str, labels: Labels) -> str:
    zh = labels(html.unescape(value))
    return html.escape(zh, quote=True) if zh is not None else value


def localize_edition(folder: Path, base: str) -> None:
    """Point page links inside `zh/`, and write the site's own words in Chinese, on every page."""
    labels = Labels(ui_table())
    pages = {p.name for p in folder.glob("*.html")}
    prefix = re.escape(base.rstrip("/") + "/")
    # (the switch's EN link is the one link that must leave `zh/`)
    link = re.compile(rf'href="{prefix}([\w.-]+\.html)((?:#[^"]*)?)"(?![^>]*data-lang="en")')
    for path in folder.glob("*.html"):
        page = path.read_text(encoding="utf-8")
        page = link.sub(lambda m: f'href="{m.group(1)}{m.group(2)}"' if m.group(1) in pages else m.group(0), page)
        path.write_text(localize(page, labels), encoding="utf-8")
    (folder.parent / "assets").mkdir(parents=True, exist_ok=True)
    (folder.parent / "assets" / "ui-zh.js").write_text(ui_script(), encoding="utf-8")


# ---------------------------------------------------------------- the check

# Five or more English words in a row, outside code: a sentence nobody translated. Names, commands
# and a term's English in brackets are shorter than that.
RUN = re.compile(r"(?:[A-Za-z][A-Za-z'’.-]*[\s,;:]+){4,}[A-Za-z][A-Za-z'’-]*")


# English that belongs: a literal quoted from a repository (an error message, a heading), in
# quotation marks, or a term's English name in brackets.
QUOTED = re.compile(r'"[^"]*"|“[^”]*”|「[^」]*」|『[^』]*』|（[^）]*）|\([^)]*\)')


BLOCK = re.compile(r"</?(?:p|li|td|th|h[1-6]|figcaption|dt|dd|div|section|summary|label|button|a|span)\b[^>]*>", re.I)
CODE = re.compile(r"<(pre|code|kbd|script|style|textarea|svg)\b[^>]*>.*?</\1>", re.S | re.I)
QUOTE_BLOCK = re.compile(r"<(blockquote|q)\b[^>]*>.*?</\1>", re.S | re.I)


def english_residue(page: str) -> list[str]:
    """Runs of English outside code, verbatim quotations and bracketed terms. Text is taken a block
    at a time, so a quotation that wraps an inline `code` span is still one quotation."""
    body = page.split("<body", 1)[-1].split(">", 1)[-1]
    allowed = ui_table().get("english_ok", [])
    body = CODE.sub(" ", body)
    body = QUOTE_BLOCK.sub(" ", body)          # a blockquote or <q> is a verbatim quotation
    found = []
    for block in BLOCK.split(body):
        text = html.unescape(re.sub(r"<[^>]+>", "", block))
        text = QUOTED.sub(" ", " ".join(text.split()))
        for phrase in allowed:
            text = text.replace(phrase, " ")
        for m in RUN.finditer(text):
            found.append(m.group(0)[:90])
    return found
