"""EN / 中文 (#116): the Chinese the site adds when a learner switches to 中文.

The course is not translated. Its key terms are: `course/06-production/terms-zh.json` gives every
glossary term a Chinese name and a one-line Chinese definition. The build uses it twice —
the glossaries carry both (hidden until the switch is on), and `assets/terms-zh.js` hands
`locale.js` the terms it names beside their first use in each part of a module's pages.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

TERMS_PATH = Path(__file__).resolve().parents[1] / "06-production" / "terms-zh.json"


def load() -> dict[str, dict]:
    return json.loads(TERMS_PATH.read_text(encoding="utf-8"))["terms"]


def stem(term: str) -> str:
    """What a term looks like in running text: `Context window (recentContext)` is written
    "context window"."""
    return re.sub(r"\s*\([^)]*\)\s*$", "", term.replace("`", "")).strip()


def _plain(fragment: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", fragment)).replace("`", "").strip()


def name_html(entry: dict | None) -> str:
    if not entry:
        return ""
    return f'<span class="gl-zh" lang="zh-Hans">{html.escape(entry["zh"])}</span>'


def def_html(entry: dict | None) -> str:
    if not entry:
        return ""
    return f'<span class="gl-zh-def" lang="zh-Hans">{html.escape(entry["def"])}</span>'


def module_glossary(rendered: str, terms: dict[str, dict]) -> str:
    """A module glossary is a list of `<li><strong>Term</strong> — definition</li>`: each gets its
    Chinese name after the term and its Chinese definition under the English one."""
    def add(m: re.Match) -> str:
        entry = terms.get(_plain(m.group(1)))
        if not entry:
            return m.group(0)
        return f'<li><strong>{m.group(1)}</strong>{name_html(entry)}{m.group(2)}{def_html(entry)}</li>'
    return re.sub(r"<li><strong>(.*?)</strong>((?:(?!<li>).)*?)</li>", add, rendered, flags=re.S)


def script(terms_by_deck: dict[str, list[dict]], terms: dict[str, dict]) -> str:
    """assets/terms-zh.js: the terms locale.js may name in running text on a module's pages. A
    generic word (`scope: "module"`) carries the modules whose glossary defines it and is only
    named there, where the page means what the glossary says."""
    modules: dict[str, list[str]] = {}
    for deck_id, items in terms_by_deck.items():
        for t in items:
            modules.setdefault(t["term"], []).append(deck_id)
    out = []
    for term, decks in sorted(modules.items()):
        entry = terms.get(term)
        if not entry or not entry.get("inline", True):
            continue
        # Beside a word in a sentence the name stands alone: "success criteria（成功标准）", not
        # a bracket inside a bracket.
        item = {"t": stem(term), "zh": re.sub(r"（[^）]*）$", "", entry["zh"]).strip()}
        if entry.get("scope") == "module":
            item["m"] = sorted(decks)
        out.append(item)
    return ("/* Generated by build_site.py from course/06-production/terms-zh.json — do not edit. */\n"
            "window.APSTermsZh = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
